### ISSUE TITLE
starter-config-client 路由定位器解析路由BUG

### ISSUE THREAD

**Issue by bojiangzhou** [choerodon/choerodon-starters#11]
![image](https://user-images.githubusercontent.com/14971397/50384140-aa959b00-06fb-11e9-965b-f48ce520768e.png)
![image](https://user-images.githubusercontent.com/14971397/50384147-b6815d00-06fb-11e9-96ee-e910a5a1b808.png)
![image](https://user-images.githubusercontent.com/14971397/50384150-c8630000-06fb-11e9-83fe-656c4b207f05.png)
BeanUtils.copyProperties 方法在反射赋值时，调用ZuulRoute.setSensitiveHeaders方法时，始终都会将customSensitiveHeaders设置为true，导致全局设置的过滤敏感头信息不生效。
建议先判断sensitiveHeaders列表非空再调这个方法。

**Comment by flyleft** [comment]
你说得对，此版本会修复这个问题，beanCopy将修改为:
```java
private static ZuulProperties.ZuulRoute beanCopy(ZuulRoute route) {
    ZuulProperties.ZuulRoute zuulRoute = new ZuulProperties.ZuulRoute();
    org.springframework.beans.BeanUtils.copyProperties(route, zuulRoute, "sensitiveHeaders");
    if (route.getSensitiveHeaders() != null && !route.getSensitiveHeaders().isEmpty()) {
        zuulRoute.setSensitiveHeaders(route.getSensitiveHeaders());
    }
    return zuulRoute;
}

```
